### ISSUE TITLE
Allow to assign a custom class to the monitor container

### ISSUE THREAD

**Issue by ingro** [bvaughn/redux-devtools-filterable-log-monitor#17]
Hello! I'm using this useful monitor but I have a minor style problem. In the app I'm working on checkboxes have a custom style to be more nice to the user's eye, but that don't fit well with the monitor checkboxes. 

I'm wondering if it would be a problem to assign a custom `className` to the monitor so I can reset checkbox's css in my stylesheet only for the monitor?

Thanks for your time!

**Comment by bvaughn** [comment]
Hi @ingro,

I'm glad you're finding the monitor useful. :)

I'm a bit reluctant to add much in the way of style overrides to the monitor since it's really only intended as a dev tool and not something end-users are going to be seeing.

That being said, I think you should be able to accomplish what you're looking for with the following:

Assuming you're doing something similar to the [demo](https://github.com/bvaughn/redux-devtools-filterable-log-monitor/blob/master/website/), then wrap your `DevTools` component when you put it into the DOM:

``` html
<div className={styles.DevToolsWrapper}>
  <DevTools/>
</div>
```

And then you can customize all checkbox inputs within the wrapped monitor like so:

``` css
.DevToolsWrapper input[type=checkbox] {
  /* Your custom styles here... */
}
```

Would this be an acceptable solution for you?

**Comment by ingro** [comment]
Thanks for the reply, your suggestion works, I tried before to wrap directly the monitor with a div but the DevTools didn't allow me to.

That's fine for me, you can close this if you wish!

**Comment by bvaughn** [comment]
Happy to hear :)
